title: PRMLT
description: Pattern Recognition and Machine Learning Toolbox
google_analytics: 
theme: jekyll-theme-midnight
github:
  repository_url: https://github.com/PRML/PRMLT
gems:
  - jekyll-mentions
