title: PRMLT
description: Pattern Recognition and Machine Learning Toolbox
google_analytics: 
show_downloads: true
repository_url: https://github.com/PRML/PRMLT
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
